---
# tasks file for create_zabbix_group
- name: create host group
  local_action:
    module: zabbix_group
    server_url: http://10.0.0.199/zabbix/
    login_user: admin
    login_password: zabbix
    state: present
    host_groups:
      - '{{ host_group }}'

